[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "9dFwos7KxyxUu6tenwAoAyDSCr4fMEZ1eTbF7watxACZ"
bonding_curve = "2RvPPes11jGU8CDZDPLZdKRGZEtWye5ZTJ4PZCKJuUoZ"
my-program = "BManGV3uwhHypt6FDZsHcdQHDsUZDLCYSfCEQ1j81xFu"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "localnet"
wallet = "/Users/phamtu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
